import { GameEvent } from "../../events/GameEvent";
import { GameState } from "../../GameState";
import { DataStore } from "../../generic/DataStore";
import { Dungeon } from "./Dungeon";
import { DungeonFloor } from "./DungeonFloor";
declare const Dungeons: DataStore<Dungeon>;
declare const DungeonFloors: DataStore<DungeonFloor>;
export { Dungeons, DungeonFloors };
export declare function getUnlockedDungeons(state: GameState): Dungeon[];
export declare function isDungeonFloorCompletedThisRun(state: GameState, floor: DungeonFloor | string): boolean;
export declare function isDungeonFloorEverCompleted(state: GameState, floor: DungeonFloor | string): boolean;
export declare function setDungeonFloorCompleted(state: GameState, floorId: string): GameState;
export declare function minMPLRecommendation(state: GameState): number;
export declare function mplIsTooLow(state: GameState): boolean;
export declare function maxMPLRecommendation(state: GameState): number;
export declare function mplIsTooHigh(state: GameState): boolean;
export declare function isStuckOnBoss(state: GameState): boolean;
export declare function registerDungeonFloorEventOddsTransformation(event: GameEvent, baseFloorIdForMoreOdds: string): void;
export declare function loadCommonDungeonLogic(): void;
