import { GameState, GameStateTransform } from "../GameState";
import { SpellElement, SpellElementType } from "../spells/Elements";
export declare const BASE_RESEARCH_EXP_PER_SEC_PER_RESEARCHER = 2;
export declare const getExpGainTags: (element: SpellElementType) => string[];
export declare function getResearcherExpPerSecAndResearcher(state: GameState): Partial<Record<SpellElement, number>>;
export declare function getResearcherExpPerSecForElements(state: GameState): Partial<Record<SpellElement, number>>;
export declare function clearResearcherExpCache(state: GameState): GameState;
export declare function getBaseResearchRate(state: GameState): number;
export declare function explainBaseResearchRate(state: GameState): string;
export declare function getTotalResearchers(state: GameState): number;
export declare function getFreeResearchers(state: GameState): number;
export declare function allocateResearchersToElement(this: any, element: SpellElementType, amount: number, isAutomatic?: boolean): GameStateTransform;
export declare function isStudyUnlocked(state: GameState): boolean;
export declare function isStudyEverUnlocked(state: GameState): boolean;
export declare function loadResearchers(): void;
