import { GameState } from "../GameState";
import type { Spell } from "../spells/Spell";
import { Spellcraft } from "./Spellcraft";
import { SpellcraftData } from "./SpellcraftData";
export declare const MAX_VATS_PER_SPELL = 2;
export declare function getSpellcraftVatsForSpell(state: GameState, spellId: string): SpellcraftData[];
export declare function canLoadMultipleVats(state: GameState, spellcraft: Spellcraft): boolean;
export declare function getVisibleSpellcrafts(state: GameState): Spellcraft[];
export declare function getVisibleSpellcraftsForSpell(state: GameState, spell: Spell): Spellcraft[];
export declare function canApplySpellcraftToSpell(state: GameState, spellId: string, spellcraft: Spellcraft, vatId?: string): boolean;
export declare function assignSpellcraftToVat(state: GameState, vatId: string, spellcraftId: string): GameState;
export declare function removeSpellcraftFromVat(state: GameState, vatId: string): GameState;
export declare function assignSpellToVat(state: GameState, vatId: string, spellId: string): GameState;
export declare const EMPTY_SPELLCRAFT_VAT: {
    spellcraftId: any;
    spellId: any;
    vatId: string;
};
export declare function createNewVat(state: GameState): GameState;
export declare function destroyVat(state: GameState, vatId: string): GameState;
export declare function getSpellcraftVats(state: GameState): SpellcraftData[];
export declare function saveSpellcraftStrategyToLoadout(state: GameState, name: string, index: number): GameState;
export declare function clearSpellcraftStrategy(state: GameState, index: number): GameState;
export declare function loadSpellcraftStrategy(state: GameState, index: number): GameState;
export declare function isSpellcraftUnlocked(state: GameState): boolean;
export declare function isSpellcraftEverUnlocked(state: GameState): boolean;
export declare function loadGenericSpellcraftTransformations(): void;
