import { GameState } from "../GameState";
import { DataStore } from "../generic/DataStore";
import { Ritual } from "./Ritual";
export declare const Rituals: DataStore<Ritual>;
export declare function getActiveRituals(state: GameState): Ritual[];
export declare function getCorruptionCap(state: GameState): number;
export declare function getCorruption(state: GameState): number;
export declare function isCorruptionHPPenaltyActive(state: GameState): boolean;
export declare function getCorruptionHPPenaltyMultiplier(state: GameState): number;
export declare function isCorruptionExpPenaltyActive(state: GameState): boolean;
export declare function getCorruptionExpPenaltyMultiplier(state: GameState): number;
export declare function isCorruptionTransmutePenaltyActive(state: GameState): boolean;
export declare function getCorruptionTransmutePenaltyMultiplier(state: GameState): number;
export declare function areRitualsUnlocked(state: GameState): boolean;
export declare function areRitualsEverUnlocked(state: GameState): boolean;
export declare function getVisibleRituals(state: GameState): Ritual[];
export declare function clearAllRitualCaches(state: GameState): GameState;
export declare function loadRitualCommonEffects(): void;
