import { GameState } from "../GameState";
import { DataStore } from "../generic/DataStore";
import { Building } from "./Building";
export type BuildingData = {
    current: number;
    turnedOn: number;
};
declare const Buildings: DataStore<Building>;
export { Buildings };
export declare const STARTING_LAND = 150;
export declare const LAND_COST_REDUCTION = 0.9925;
export declare const LOW_COST_SCALE_MULTIPLIER = 1.1;
export declare function getTotalLand(state: GameState): number;
export declare function clearLandCache(state: GameState): GameState;
export declare function getUsedLand(state: GameState): number;
export declare function getFreeLand(state: GameState): number;
export declare function getBuildingAmount(state: GameState, building: Building): number;
export declare function getBuildingAmountTurnedOn(state: GameState, building: Building): number;
export declare function setBuildingsTurnedOn(building: Building, amount: number, state: GameState): GameState;
export declare function changeBuildingsTurnedOn(building: Building, amount: number, state: GameState): GameState;
export declare function shouldRecoverCostFromDemolishing(state: GameState): boolean;
export declare const BuildingAmountListeners: DataStore<(state: GameState, building: Building) => GameState>;
